#!/usr/bin/env sh
set -eu

SERVICE="${SERVICE:-ops}"

case "$SERVICE" in
  ops|frontend|qs-operating-system)
    SERVICE=ops
    IMAGE_NAME=qs-operating-system
    DOCKERFILE=build/Dockerfile
    CONTAINER_NAME=qs-operating-system
    PACKAGE_SUFFIX=ops
    APP_PORT="${APP_PORT:-3000}"
    NETWORK_NAME="${NETWORK_NAME:-infra-network}"
    HEALTH_PATH="${HEALTH_PATH:-/}"
    ;;
  *)
    echo "Unsupported SERVICE: $SERVICE" >&2
    exit 1
    ;;
esac

IMAGE_TAG="sha-${DEPLOY_SHA:-}"
DEPLOY_IMAGE_PACKAGE="${DEPLOY_IMAGE_PACKAGE:-deploy-image-${PACKAGE_SUFFIX}.tar.gz}"

export SERVICE IMAGE_NAME DOCKERFILE CONTAINER_NAME PACKAGE_SUFFIX APP_PORT NETWORK_NAME HEALTH_PATH
export IMAGE_TAG DEPLOY_IMAGE_PACKAGE

if [ "${IMAGE_METADATA_PRINT:-}" = "1" ]; then
  cat <<EOF
SERVICE=${SERVICE}
IMAGE_NAME=${IMAGE_NAME}
DOCKERFILE=${DOCKERFILE}
CONTAINER_NAME=${CONTAINER_NAME}
PACKAGE_SUFFIX=${PACKAGE_SUFFIX}
APP_PORT=${APP_PORT}
NETWORK_NAME=${NETWORK_NAME}
HEALTH_PATH=${HEALTH_PATH}
IMAGE_TAG=${IMAGE_TAG}
DEPLOY_IMAGE_PACKAGE=${DEPLOY_IMAGE_PACKAGE}
EOF
fi
